version: '3.1'
services:
  app-way:
    container_name: spring-postgresql
    image: springboot-postgresql
    build: ./
    ports:
      - "8085:8080"
    depends_on:
      - postgresqldb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testDB
  postgresqldb:
    container_name: postgresql-server
    image: postgres
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testDB